[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[project]
name = "ml_ops_project"
version = "0.0.1" # major.minor.patch
description = "Repository for the DTU Machine Learning Operations project."
authors = [
    { name = "Vincent Van Schependom", email = "vincent.van.schependom@gmail.com" },
    { name = "Malthe August Bresler" },
    { name = "Sara Maria Bjørn Andersen" },
    { name = "Frederik Ravnborg" },
]
license = { file = "LICENSE" }
keywords = ["machine learning", "MLOps"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.8.4",
    "fastapi==0.135.3",
    "jupyter>=1.1.1",
    "loguru>=0.7.3",
    "pytorch-lightning>=2.6.1",
    "notebook>=7.5.5",
    "torch>=2.2.2",
    "transformers>=5.5.3",
    "typer==0.24.1",
    "uvicorn==0.44.0",
    "wandb>=0.25.1",
    "torchmetrics>=1.9.0",
    "numpy==2.4.4",
    "google-api-python-client>=2.194.0",
    "dvc-gs>=3.0.2",
    "dvc>=3.67.1",
    "python-dotenv>=1.2.2",
    "markdown>=3.10.2",
    "pydantic>=2.13.0",
    "hydra-core>=1.3.2",
    "prometheus-client>=0.25.0",
    "nltk>=3.9.4",
    "evidently>=0.7.21",
    "locust>=2.43.4",
    "google-cloud-run>=0.16.0",
]

# Optional dependency groups, which can be installed using:
#    uv sync --group dev
# To install all groups, use:
#    uv sync --all-groups
[dependency-groups]
dev = [
    "coverage==7.13.5",
    "invoke==3.0.3",
    "mkdocs-material>=9.7.6",
    "mkdocs>=1.6.0",
    "pre-commit==4.5.1",
    "pytest==9.0.3",
    "ruff==0.15.10",
    "mkdocstrings[python]>=1.0.3",
    "pytest-cov>=7.1.0",
    "httpx>=0.28.1",
]
inference-api = [
    "fastapi>=0.135.3",
    "google-cloud-storage>=3.10.1",
    "hydra-core>=1.3.2",
    "pydantic>=2.13.0",
    "python-dotenv>=1.2.2",
    "pytorch-lightning>=2.6.1",
    "torch>=2.2.2",
    "torchmetrics>=1.9.0",
    "transformers>=5.5.3",
    "uvicorn>=0.44.0",
    "wandb>=0.25.1",
]




[tool.ruff]
line-length = 120

# This part triggers coverage automatically when you run 'pytest'
[tool.pytest.ini_options]
addopts = "--cov=src/ml_ops_project --cov-report=term-missing"
testpaths = ["tests"]
pythonpath = ["src"]
filterwarnings = [
    "ignore:The `Scope.user` setter is deprecated.*:DeprecationWarning:wandb\\.analytics\\.sentry",
    "ignore:Read the `app_url` setting.*:DeprecationWarning:wandb\\.apis\\.public\\.api",
]

# This part fine-tunes the coverage engine
[tool.coverage.run]
source = ["src/ml_ops_project"]
omit = [
    "tests/*",
    "**/__init__.py"
]

[tool.coverage.report]
show_missing = true
precision = 2

[tool.uv]
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'x86_64'",
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]
