# This action can be called by a GitHub workflow to authenticate with GCP
# such that the files tracked by the Data Version Control (DVC) bucket
# can be accessed.

name: 'Auth with GCP'
description: 'Authenticate to GCP using a service account key.'

inputs:
  GCLOUD_SERVICE_KEY:
    description: 'GCP Service Account Key'
    required: true

runs:
    using: "composite"
    steps:

    - name: 'Authenticate to GCP'
      uses: google-github-actions/auth@v2
      with:
        # This is the JSON file from GCP. It was added to the GitHub secrets as 'GCLOUD_SERVICE_KEY'.
        credentials_json: ${{ inputs.GCLOUD_SERVICE_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
